### ISSUE TITLE
"CenteralError.peripheralNotConnected" Does Not Exist

### ISSUE THREAD

**Issue by jcady92** [troystribling/BlueCap#7]
Here's an excerpt from the simple Central example:

```
let peripheralDiscoveredFuture = peripheralConnectFuture.flatmap {(peripheral, connectionEvent) -> Future<Peripheral> in
    if peripheral.state == .Connected {
        return peripheral.discoverPeripheralServices([serviceUUID])
    } else {
        let promise = Promise<Peripheral>()
        promise.failure(CenteralError.peripheralNotConnected)
        return promise.future
    }
}
```

Two things:
1. `CenteralError` should be `CentralError`
2. `peripheralNotConnected` is not a member of the CentralError enum.  There is only one member, `IsScanning`.

**Comment by jcady92** [comment]
The enum doesn't work with that anyway, given promise.failure accepts a NSError as an argument.

Maybe you meant `BCError.peripheralDisconnected`?

**Comment by troystribling** [comment]
The example was taken from the Central example here https://github.com/troystribling/BlueCap/blob/master/Examples/Central/Central/ViewController.swift#L13-28. 

CenteralError.peripheralNotConnected is an application defined error. I will update the example to include the definition so that there is not any confusion.
